version: '{{cookiecutter.compose_version}}'
x-images:
  env: &env {env_file: [.env, docker.env]}
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build: &build
      context: "."
      args: &args
        HOST_USER_UID: "${HOST_USER_UID:-1000}"
        BUILDKIT_INLINE_CACHE: "1"
        ZEO_BASE_IMAGE: "${ZEO_BASE_IMAGE:-{{cookiecutter.zeo_base_image}}}"
        BUILD_BASE_IMAGE: "${PLONE_BASE_IMAGE:-{{cookiecutter.base_builder_image}}}"
        PROD_BASE_IMAGE: "${PLONE_BASE_IMAGE:-{{cookiecutter.base_prod_image}}}"
        PLONE_VERSION: "${PLONE_VERSION:-{{cookiecutter.plone_ver}}}"
        HELPERS: "${HELPERS_IMAGE:-{{cookiecutter.helpers_image}}}"
        # BASE: "${{'{'}}{{cookiecutter.app_type.upper()}}}}_BASE_IMAGE:-{{cookiecutter.debian_image}}}"
        PY_VER: "${PLONE_PY_VER:-{{cookiecutter.py_ver}}}"
        WITH_VSCODE: "${WITH_VSCODE:-0}"
        VSCODE_VERSION: "${VSCODE_VERSION-}"
services:
{%- if not cookiecutter.remove_cron %}
  db: {<<: [ *{{cookiecutter.app_type}} ], build: {<<: [ *build ], dockerfile: Dockerfile.zeo}}
  cron: {<<: [ *{{cookiecutter.app_type}} ]}
{%-endif%}
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
